// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/api/categories/[id].ts";
import * as $3 from "./routes/api/categories/index.ts";
import * as $4 from "./routes/api/foods/[id].ts";
import * as $5 from "./routes/api/foods/index.ts";
import * as $6 from "./routes/api/review/index.ts";
import * as $7 from "./routes/categories.tsx";
import * as $8 from "./routes/category/[id].tsx";
import * as $9 from "./routes/food/[id].tsx";
import * as $10 from "./routes/foods.tsx";
import * as $11 from "./routes/index.tsx";
import * as $12 from "./routes/search.tsx";
import * as $$0 from "./islands/CategoryInput.tsx";
import * as $$1 from "./islands/CreateReview.tsx";
import * as $$2 from "./islands/DeleteButton.tsx";
import * as $$3 from "./islands/FoodInput.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/api/categories/[id].ts": $2,
    "./routes/api/categories/index.ts": $3,
    "./routes/api/foods/[id].ts": $4,
    "./routes/api/foods/index.ts": $5,
    "./routes/api/review/index.ts": $6,
    "./routes/categories.tsx": $7,
    "./routes/category/[id].tsx": $8,
    "./routes/food/[id].tsx": $9,
    "./routes/foods.tsx": $10,
    "./routes/index.tsx": $11,
    "./routes/search.tsx": $12,
  },
  islands: {
    "./islands/CategoryInput.tsx": $$0,
    "./islands/CreateReview.tsx": $$1,
    "./islands/DeleteButton.tsx": $$2,
    "./islands/FoodInput.tsx": $$3,
  },
  baseUrl: import.meta.url,
};

export default manifest;
